/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { PhotoUpdateManyWithoutUsersInput } from "./PhotoUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { VideoUpdateManyWithoutUsersInput } from "./VideoUpdateManyWithoutUsersInput";
import { AudioUpdateManyWithoutUsersInput } from "./AudioUpdateManyWithoutUsersInput";
import { PdfUpdateManyWithoutUsersInput } from "./PdfUpdateManyWithoutUsersInput";
import { StatisticsUpdateManyWithoutUsersInput } from "./StatisticsUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => PhotoUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PhotoUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PhotoUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  photos?: PhotoUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => VideoUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VideoUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VideoUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  videos?: VideoUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AudioUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AudioUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AudioUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  audioItems?: AudioUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PdfUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PdfUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PdfUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  pdfs?: PdfUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => StatisticsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StatisticsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StatisticsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  statisticsItems?: StatisticsUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
